#!/usr/bin/env bash

# abort script on commands yielding non-zero retval
set -e
# verbose - print each command before executing it
# set -v

PORT=${PORT:-5050}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${DIR}"

fatal () {
    echo "FATAL: ${*}"
    exit 1
}

if [[ ! -d env ]]; then
    echo "virtualenv missing, initializing..."
    virtualenv env
    source env/bin/activate
    pip install mkdocs
else
    source env/bin/activate
fi

if [[ ! -d notes ]]; then
    fatal "no notes dir"
fi

cd notes
mkdocs serve --dev-addr localhost:${PORT}
